#!/usr/bin/env bash
# Transfers a file to a remote server's home directory using SCP

# Check if exactly 4 arguments are passed
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning arguments to variables for readability
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Use scp with strict host key checking disabled
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "${USER}@${IP}":~/
