#!/usr/bin/env bash
# Script to install and configure Nginx web server

# Update and install
sudo apt-get update -y
sudo apt-get install nginx -y

# Configure default page
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Ensure proper permissions
sudo chmod 644 /var/www/html/index.html
sudo chown www-data:www-data /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
