#!/usr/bin/env bash
# Configures a new Ubuntu machine to perform a 301 redirect from /redirect_me

# Update package lists
apt-get update -y

# Install nginx
apt-get install -y nginx

# Configure 301 redirection
sed -i '/^\s*location \/ {/i \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }\n' /etc/nginx/sites-available/default

# Reload nginx (no systemctl)
service nginx restart
