#!/usr/bin/env bash
# Configures a new Ubuntu machine to perform a 301 redirect from /redirect_me

# Install nginx
apt-get update -y
apt-get install -y nginx

# Add 301 redirection config to nginx default site
sed -i '/^\s*location \/ {/i \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }\n' /etc/nginx/sites-available/default

# Restart nginx (without systemctl)
service nginx restart
