#!/usr/bin/env bash
# Configures a custom 404 page with Nginx that returns "Ceci n'est pas une page"

# Install nginx
apt-get update -y
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update Nginx default site config
sed -i '/^\s*error_page 404 /d' /etc/nginx/sites-available/default
sed -i '/^\s*location \/ {/a \
    error_page 404 /custom_404.html;\n\
    location = /custom_404.html {\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
